### ISSUE TITLE
Strings not in AMOS

### ISSUE THREAD

**Issue by dinism** [sh-csg/moodle-availability_user#1]
Thanks for the plugin.
I can't find it in AMOS. I'm PT-PT translator

**Comment by sh-csg** [comment]
Maybe there was a short delay in publication on AMOS (plugin was approved only 45 Minutes ago) - now you can find it in AMOS, thanks a lot for contributing!

**Comment by dinism** [comment]
Thanks a LOT. Keep the good work.
Translation DONE.
