### ISSUE TITLE
Keine Auswahl möglich

### ISSUE THREAD

**Issue by BiLachner** [sh-csg/moodle-availability_user#2]
Hallo 

Ich habe auf einer unserer Testinstanzen (mit einem neuen Aussehen/Theme) das Problem, das sich keine einzelne Person anwählen kann.
![Screenshot_20220106_065901](https://user-images.githubusercontent.com/13196996/148336363-83e28c1c-2b36-4f39-9c5b-1c2630f3fa70.png)
Sie sehen alle markiert aus, beim Anklicken einzelner Namen passiert nichts sichtbares (außer das es etwas dunkler ist). Beim Abspeichern, werden die Einstellungen auch nicht mit abgespeichert.
Die Breite des Auswahlfeld passt sich nicht an die Größe der Namen an.

Es kann natürlich sein, dass das ein Fehler des Themes ist ... aber dann wäre es auch interessant zu wissen, was das Problem ist, da wir das für uns entwickelt bekommen haben!

Danke ;-)

**Comment by BiLachner** [comment]
Ah, noch was beobachtet. Ich habe doch was ausgewählt:
![Screenshot_20220106_071311](https://user-images.githubusercontent.com/13196996/148337338-2ec733b9-f806-4f33-82ad-c7d594f61dbf.png)

In den Einstellungen ist der Ausgewählte nur schwach hervorgehoben.
![Screenshot_20220106_071354](https://user-images.githubusercontent.com/13196996/148337395-2564ee11-7ddb-4367-b5df-c6523557786b.png)

Soll ich mal raussuchen, welche Klassen da eine Rolle spielen?

**Comment by BiLachner** [comment]
Hier, wenn ich in die EInstellungen gehe, dann sieht man keinen Unterschied
![Screenshot_20220106_072042](https://user-images.githubusercontent.com/13196996/148338371-ed8dc3eb-1174-487e-91c9-beec542e5b5d.png)


Wenn ich den Testschüler drei ausgewählt (angeklickt) habe kommt eine ID dazu:

![Screenshot_20220106_072106](https://user-images.githubusercontent.com/13196996/148338453-504bbe95-23a2-4c59-b20f-1774bc162345.png)

**Comment by sh-csg** [comment]
Liebe Birgit,
vielen Dank für deinen Bugreport - um welche Moodle-Version und um welches Theme handelt es sich denn? Tritt das Problem auch mit einem anderen Theme auf?
Viele Grüße
Stefan

**Comment by BiLachner** [comment]
Ah ja ... ist moodle 3.9

Wie erwähnt ist es eine neu erstelltes Theme in unserem Design (basierend auf Boost), das voreingestellt ist. Aaaaber ... daran hatte ich gar nicht gedacht, ich kann auch auf ein altes Design wechseln und da sieht es schon besser aus. Nur die Breite passt sich nicht an bzw. ist etwas knapp.

![Screenshot_20220106_075044](https://user-images.githubusercontent.com/13196996/148346331-4e51c929-877d-48cc-bc11-19b93f29e8b0.png)

Also ist auf jeden Fall ein Fehler im Theme dabei, vermute ich mal.

**Comment by BiLachner** [comment]
Sorry, das ich so viel reinschreibe ... ich habe probiert, woran es liegt und da fällt mir auf: wenn ich Gruppen bei der Voraussetzung auswähle, dann sieht die Auswahlbox anders aus und da kann ich auch in dem neuen Theme etwas wählen.

![Screenshot_20220106_084356](https://user-images.githubusercontent.com/13196996/148347329-7565580d-bcc2-481e-9b47-03270d3664eb.png)

![Screenshot_20220106_084414](https://user-images.githubusercontent.com/13196996/148347364-36edc051-23f0-4a43-bdce-a3c12c6e058e.png)

Vielleicht wäre diese Art der Auswahl besser!?

**Comment by sh-csg** [comment]
Danke für die Anregung! Ich teste das bei nächster Gelegenheit.

**Comment by sh-csg** [comment]
Ich habe das jetzt überprüft: 
Bei availability_group ist das ein "normales" select-Element, ohne multiple-Attribut. Das dürfte den Unterschied machen. Schaut da doch bitte mal bei eurem Theme nach.
Die Breiten-Begrenzung kommt von außen, ich habe damit mal ein bisschen experimentiert. Wenn man sie erhöht, dann verschwindet u.a. in einigen Settings das Bedienelement zum Löschen. Daher würde ich das zumindest auf diesem Wege nicht umsetzen.
